[package]
name = "senpi-desktop-backend-atspi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[target.'cfg(target_os = "linux")'.dependencies]
atspi.workspace = true
senpi-desktop-core = { path = "../senpi-desktop-core" }
tokio = { workspace = true, features = ["time"] }
zbus.workspace = true
