// team-guide.mjs - render the member-facing field manual (guide.md) and the short
// bootstrap trigger a new thread reads on startup. Pure string builders, no I/O.
//
// The manual is the durable, two-channel replacement for per-prompt guidance: the leader
// writes it once at team creation, and every member thread is told to READ it instead of
// receiving the rules inline each turn.

export function codexThreadLink(threadId) {
	return `codex://threads/${threadId}`;
}

function memberLine(member) {
	const thread = member.threadId ? ` | thread ${member.threadId} (${codexThreadLink(member.threadId)})` : " | thread not created yet";
	const wt = member.worktree?.path ? ` | worktree ${member.worktree.path}` : "";
	const name = member.name ? ` "${member.name}"` : "";
	const title = member.threadTitle ? ` | thread title \`${member.threadTitle}\`` : "";
	return `- **${member.id}**${name} (${member.lens}) - ${member.focus}${member.deliverable ? ` -> ${member.deliverable}` : ""}${title}${thread}${wt} [${member.status}]`;
}

function worktreeSection(team) {
	if (!team.worktree?.enabled) {
		return `## Worktrees

This team does not use isolated git worktrees. Work in the shared repository checkout
the leader is running from. If your changes would collide with another member's files,
that is a coordination signal: mark yourself \`blocked\` and tell the leader at once.`;
	}
	const lines = team.members
		.filter((m) => m.worktree?.path || m.worktree?.branch)
		.map((m) => {
			const thread = m.threadId ? `; thread ${codexThreadLink(m.threadId)}` : "";
			return `- **${m.id}**: worktree \`${m.worktree.path ?? "(assign with bind-thread --cwd)"}\` on branch \`${m.worktree.branch ?? team.worktree.baseBranch}\`${thread}`;
		});
	return `## Worktrees (ISOLATION IS ON - this is not optional for you)

This team runs each member in its own git worktree branched off \`${team.worktree.baseBranch}\`.
**You MUST work only inside your own worktree.** The very first thing you do is \`cd\` into it;
every edit, command, and commit happens there. Never touch another member's worktree, and
never edit files outside your assigned scope. Commit your work so the leader can integrate it.
Before editing, verify that your assigned worktree exists and contains repo files. If the path is
missing, empty, or does not look like a git worktree/repository yet, send \`BLOCKED: worktree not ready\`
to the leader and wait instead of editing any parent checkout or empty directory.

If Codex returns only \`pendingWorktreeId\` while the leader is creating a worktree-backed member
thread, the thread is not ready yet. The leader must wait until Codex surfaces a real thread id,
then bind that real id and send the bootstrap.

${lines.length ? lines.join("\n") : "- (worktree paths are assigned as threads are bound; read team.json for yours)"}`;
}

export function buildGuide(team) {
	const artifacts = team.paths?.artifacts ?? ".omo/teams/<session_id>/artifacts";
	const teamJson = team.paths?.team ?? ".omo/teams/<session_id>/team.json";
	const roster = team.members.length ? team.members.map(memberLine).join("\n") : "- (no members yet)";
	return `# Team ${team.teamName} - Member Field Manual

> Auto-generated by the teammode script. This file is the single source of truth for how
> this team works. Re-read it whenever you are unsure - do not improvise the protocol.

- Team: **${team.teamName}** (id \`${team.teamId}\`)
- Team state: \`${teamJson}\`
- Thread title convention: \`${team.threadTitleConvention}\` - each member's thread takes its OWN title from its name (your row below shows yours); two members never share a title

## Who you are (your identity is fixed)

**You are a member of team ${team.teamName}, not a generic assistant.** You own exactly one
slice of this team's work - the focus and deliverable assigned to your id below - and you are
accountable for it end to end. Read your row, internalize it, and act as that owner for the
whole session. Do not drift into other members' scope.

${roster}

## Leader

**The main session is the leader. There is no other leader, and you are not it.** You report
to the leader, take direction from the leader, and send your results to the leader. Peers
coordinate with each other, but the leader owns the final decision and integration.

## Communication rules (hard rules)

- **All communication between team members, and from you to the leader, is in English.** This
  is mandatory regardless of the language the task was given in.
- **Exception: when the END USER addresses you directly, reply in the user's own language.**
  Team-internal traffic stays English; user-facing replies match the user.
- **Reach the leader and your peers with \`codex_app.send_message_to_thread\` - not by narrating in
  your own thread, where no one reads it.** The address book is in team.json: the leader thread id
  is \`leader.sessionId\`, and each peer thread id is its \`members[].threadId\`.
- **When you mention a Codex thread, include its app link too:** \`codex://threads/<threadId>\`.
  These links are the fastest way for the leader to reopen worktree-backed member threads.
- **Push a short message at each of these moments - never batch them into one report at the end:**
  - to the **leader**: every finding or decision, every file or sub-task you finish, a
    \`WORKING: <focus> - <phase>\` heartbeat every few tool calls so you never look stale, a
    \`BLOCKED: <reason>\` the instant you cannot proceed, and your result the moment your slice is done.
  - to a **peer**: the instant you learn anything that touches their slice - a shared finding, a
    changed assumption, an interface they depend on. When unsure who owns it, send it to the leader.
- **Going quiet is the only failure.** Many small lean messages beat one end-of-work dump; keep
  every message short. Your heartbeats are what let the leader relax and leave you to work: a leader
  who can see your progress has no reason to interrupt you, while silence forces it to break in and
  ask where things stand. Frequent lean updates buy you uninterrupted focus.

## Artifacts (how you hand work off)

Exchange files and memos through the team artifacts directory:

\`${artifacts}\`

Drop deliverables, notes, diffs, and findings there as files, and reference them by path in
your messages instead of pasting large content into a thread. Treat it as the team's shared
desk: if a peer or the leader needs something from you, leave it in artifacts and point them to it.

${worktreeSection(team)}

## Done means reported and verified

Your slice is done only when (1) the deliverable exists, (2) you have evidence it works, and
(3) you have reported it to the leader. Until all three are true, keep going.`;
}

export function buildMemberPrompt(team, id) {
	const member = team.members.find((m) => m.id === id);
	if (!member) throw new Error(`no member with id "${id}"`);
	const guide = team.paths?.guide ?? ".omo/teams/<session_id>/guide.md";
	const teamJson = team.paths?.team ?? ".omo/teams/<session_id>/team.json";
	const where = member.cwd
		? `Work inside \`${member.cwd}\`.`
		: team.worktree?.enabled
			? "Wait for the leader to bind your worktree cwd before editing."
			: "Work from the repository root unless your manual assigns a worktree.";
	const threadLink = member.threadId ? `\nYour Codex thread link is ${codexThreadLink(member.threadId)}. Include it when reporting handoffs or worktree status.` : "";
	const readiness =
		team.worktree?.enabled
			? "\nBefore editing, verify that your assigned worktree exists and contains repo files. If this prompt arrived before your Codex worktree checkout is ready, or the path is missing, empty, or not a git worktree/repository yet, report `BLOCKED: worktree not ready` to the leader and wait."
			: "";
	return `You are member ${member.id}${member.name ? ` (${member.name})` : ""} of team ${team.teamName} - owner of: ${member.focus}. Your thread title is \`${member.threadTitle}\`.
FIRST read your field manual at \`${guide}\`, then the team state at \`${teamJson}\`; they define your scope, deliverable, the leader, the artifacts directory, and the communication rules.
${where}${threadLink}${readiness}
Communicate with the team and leader in English; reply to the end user in the user's own language.
Start now. Push updates to the leader and relevant peers with \`codex_app.send_message_to_thread\` as you work - findings, \`WORKING:\` heartbeats, and \`BLOCKED:\` the instant you stall - never just one report at the end.`;
}
