import { z } from "zod"

export const HookNameSchema = z.enum([
  "todo-continuation-enforcer",
  "session-notification",
  "comment-checker",
  "tool-output-truncator",
  "question-label-truncator",
  "directory-agents-injector",
  "directory-readme-injector",
  "empty-task-response-detector",
  "think-mode",
  "model-fallback",
  "anthropic-context-window-limit-recovery",
  "preemptive-compaction",
  "rules-injector",
  "background-notification",
  "auto-update-checker",
  "startup-toast",
  "keyword-detector",
  "agent-usage-reminder",
  "non-interactive-env",
  "interactive-bash-session",

  "tool-pair-validator",
  "monitor-status-injector",
  "ralph-loop",
  "category-skill-reminder",

  "compaction-context-injector",
  "compaction-todo-preserver",
  "claude-code-hooks",
  "auto-slash-command",
  "edit-error-recovery",
  "json-error-recovery",
  "delegate-task-retry",
  "prometheus-md-only",
  "sisyphus-junior-notepad",
  "team-tool-gating",
  "no-sisyphus-gpt",
  "no-hephaestus-non-gpt",
  "hephaestus-agents-md-injector",
  "start-work",
  "atlas",
  "unstable-agent-babysitter",
  "task-resume-info",
  "stop-continuation-guard",
  "tasks-todowrite-disabler",
  "runtime-fallback",
  "write-existing-file-guard",
  "notepad-write-guard",
  "bash-file-read-guard",
  "hashline-read-enhancer",
  "read-image-resizer",
  "todo-description-override",
  "webfetch-redirect-guard",
  "fsync-skip-warning",
  "plan-format-validator",
  "legacy-plugin-toast",
])

export type HookName = z.infer<typeof HookNameSchema>
