import { expect, test } from "bun:test"
import { cp, readFile, stat, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { repo, git } from "../backends/git-fixture"
import { captureBaseline } from "../git/baseline"
import { captureDeltaPatch } from "../git/delta"
import { mergeIsolatedChanges } from "./index"
import { commitToBranch, mergeTaskBranch, IsolationCommitReplayError } from "./branch-mode"

async function setup(nested = false) {
  const f = await repo()
  if (nested) {
    const inner = await repo()
    await cp(inner.repoRoot, join(f.repoRoot, "inner"), { recursive: true })
  }
  const baseline = await captureBaseline(f.repoRoot)
  const isolationDir = join(f.root, "child")
  await cp(f.repoRoot, isolationDir, { recursive: true })
  const options = { ...f, baseline, isolationDir, id: "test", artifactsDir: join(f.root, "artifacts"), apply: true, mode: "patch" as const }
  return options
}
async function commit(dir: string, name: string, text = `${name}\n`) {
  await writeFile(join(dir, name), text)
  await git(dir, "add", name)
  await git(dir, "commit", "-m", name)
}
async function text(dir: string, name = "tracked") { return readFile(join(dir, name), "utf8") }

test("patch applies child changes and writes readable artifacts and summary", async () => {
  const f = await setup()
  await writeFile(join(f.isolationDir, "tracked"), "child\n")
  const result = await mergeIsolatedChanges(f)
  expect(result.kind).toBe("applied")
  expect(result.changes_applied).toBe(true)
  expect(result.files_changed).toBe(1)
  expect(await text(f.repoRoot)).toBe("child\n")
  expect(await git(f.repoRoot, "status", "--porcelain")).toBe("M tracked")
  expect(await readFile(result.patch_path!, "utf8")).toContain("+child")
  expect(await readFile(result.summary_path, "utf8")).toContain("applied")
})
test("moved context fails closed atomically, retaining patch and git conflict", async () => {
  const f = await setup()
  await writeFile(join(f.isolationDir, "tracked"), "child\n")
  await writeFile(join(f.isolationDir, "new"), "must not land\n")
  await writeFile(join(f.repoRoot, "tracked"), "parent\n")
  const before = await git(f.repoRoot, "diff", "--binary")
  const result = await mergeIsolatedChanges(f)
  expect(result.kind).toBe("not-applied")
  expect(result.changes_applied).toBe(false)
  expect(result.conflict).toContain("patch does not apply")
  expect(result.manual_command).toBe(`git apply --3way ${result.patch_path}`)
  expect(await git(f.repoRoot, "diff", "--binary")).toBe(before)
  expect(await git(f.repoRoot, "ls-files", "--others", "--exclude-standard")).toBe("")
  expect(await readFile(result.patch_path!, "utf8")).toContain("must not land")
})
test("same delta twice is already-applied", async () => {
  const f = await setup()
  await writeFile(join(f.isolationDir, "tracked"), "child\n")
  const delta = await captureDeltaPatch(f.isolationDir, f.baseline)
  expect((await mergeIsolatedChanges({ ...f, delta })).kind).toBe("applied")
  const result = await mergeIsolatedChanges({ ...f, delta })
  expect(result.kind).toBe("already-applied")
  expect(result.changes_applied).toBe(true)
  expect(await text(f.repoRoot)).toBe("child\n")
})
test("apply false retains artifacts without parent changes or task branch", async () => {
  const f = await setup()
  await commit(f.isolationDir, "new")
  for (const mode of ["patch", "branch"] as const) {
    const result = await mergeIsolatedChanges({ ...f, mode, apply: false })
    expect(result.kind).toBe("retained")
    expect(result.changes_applied).toBe(false)
    expect(await readFile(result.patch_path!, "utf8")).toContain("+new")
  }
  expect(await git(f.repoRoot, "status", "--porcelain")).toBe("")
  expect(await git(f.repoRoot, "branch", "--list", "omo/task/*")).toBe("")
})
test("empty delta writes no-changes summary", async () => {
  const f = await setup()
  const result = await mergeIsolatedChanges(f)
  expect(result.kind).toBe("no-changes")
  expect(result.files_changed).toBe(0)
  expect(await readFile(result.summary_path, "utf8")).toContain("no-changes")
})
test("clean branch preserves two child commits, merges onto parent HEAD and deletes branch", async () => {
  const f = await setup()
  await commit(f.isolationDir, "first")
  await commit(f.isolationDir, "second")
  const branch = await commitToBranch(f.isolationDir, f.repoRoot, f.id, f.baseline)
  expect(branch.branchName).toBe("omo/task/test")
  expect(await git(f.repoRoot, "rev-list", "--count", `${branch.baseSha}..${branch.branchName}`)).toBe("2")
  await commit(f.repoRoot, "parent")
  const result = await mergeTaskBranch(f.repoRoot, branch)
  expect(result.kind).toBe("branch-merged")
  expect(await git(f.repoRoot, "log", "-3", "--format=%s")).toBe("second\nfirst\nparent")
  expect(await git(f.repoRoot, "branch", "--list", branch.branchName!)).toBe("")
})
test("branch trailing leftovers use callback without changing child or parent WIP", async () => {
  const f = await setup()
  await commit(f.isolationDir, "first")
  await writeFile(join(f.isolationDir, "leftover"), "left\n")
  const result = await mergeIsolatedChanges({ ...f, mode: "branch", commitMessage: async () => "generated" })
  expect(result.kind).toBe("branch-merged")
  expect(await git(f.repoRoot, "log", "-2", "--format=%s")).toBe("generated\nfirst")
  expect(await git(f.isolationDir, "status", "--porcelain")).toBe("?? leftover")
})
test("branch stashes staged, unstaged and untracked parent WIP and restores byte-identically", async () => {
  const f = await setup()
  await commit(f.isolationDir, "new")
  await writeFile(join(f.repoRoot, "tracked"), "staged\n")
  await git(f.repoRoot, "add", "tracked")
  await writeFile(join(f.repoRoot, "tracked"), "unstaged\n")
  await writeFile(join(f.repoRoot, "untracked"), Buffer.from([0, 255, 2]))
  const staged = await git(f.repoRoot, "diff", "--cached", "--binary")
  const unstaged = await git(f.repoRoot, "diff", "--binary")
  const result = await mergeIsolatedChanges({ ...f, mode: "branch" })
  expect(result.kind).toBe("branch-merged")
  expect(await git(f.repoRoot, "diff", "--cached", "--binary")).toBe(staged)
  expect(await git(f.repoRoot, "diff", "--binary")).toBe(unstaged)
  expect(await readFile(join(f.repoRoot, "untracked"))).toEqual(Buffer.from([0, 255, 2]))
  expect(await git(f.repoRoot, "stash", "list")).toBe("")
})
test("branch conflict aborts entire range and keeps recoverable branch", async () => {
  const f = await setup()
  await commit(f.isolationDir, "first")
  await commit(f.isolationDir, "tracked", "child\n")
  await commit(f.repoRoot, "tracked", "parent\n")
  const head = await git(f.repoRoot, "rev-parse", "HEAD")
  const result = await mergeIsolatedChanges({ ...f, mode: "branch" })
  expect(result.kind).toBe("branch-merge-failed")
  expect(result.changes_applied).toBe(false)
  expect(result.conflict).toBeTruthy()
  expect(result.branch_name).toBe("omo/task/test")
  expect(await git(f.repoRoot, "rev-parse", "HEAD")).toBe(head)
  expect(await git(f.repoRoot, "status", "--porcelain")).toBe("")
  expect(await git(f.repoRoot, "branch", "--list", result.branch_name!)).toContain("omo/task/test")
})
test("stash restore collision reports warning and never drops user's stash", async () => {
  const f = await setup()
  await commit(f.isolationDir, "tracked", "child\n")
  await writeFile(join(f.repoRoot, "tracked"), "parent WIP\n")
  const result = await mergeIsolatedChanges({ ...f, mode: "branch" })
  expect(result.kind).toBe("branch-merged")
  expect(result.changes_applied).toBe(true)
  expect(result.warning).toContain("stash")
  expect(await git(f.repoRoot, "stash", "list")).toContain("omo-task-merge")
  expect(await git(f.repoRoot, "show", "stash@{0}:tracked")).toBe("parent WIP")
})
test("nested patches land after root and preserve staged nested WIP", async () => {
  const f = await setup(true)
  await writeFile(join(f.isolationDir, "tracked"), "root\n")
  await writeFile(join(f.isolationDir, "inner/tracked"), "nested\n")
  await writeFile(join(f.repoRoot, "inner/wip"), "user\n")
  await git(join(f.repoRoot, "inner"), "add", "wip")
  const result = await mergeIsolatedChanges(f)
  expect(result.kind).toBe("applied")
  expect(result.partial).toBeUndefined()
  expect(await text(f.repoRoot, "inner/tracked")).toBe("nested\n")
  expect(await git(join(f.repoRoot, "inner"), "status", "--porcelain")).toBe("A  wip")
  expect(await git(join(f.repoRoot, "inner"), "stash", "list")).toBe("")
  expect(result.nested_patch_paths).toHaveLength(1)
})
test("root failure leaves nested repo untouched", async () => {
  const f = await setup(true)
  await writeFile(join(f.isolationDir, "tracked"), "child\n")
  await writeFile(join(f.isolationDir, "inner/tracked"), "nested\n")
  await writeFile(join(f.repoRoot, "tracked"), "parent\n")
  const result = await mergeIsolatedChanges(f)
  expect(result.kind).toBe("not-applied")
  expect(await text(f.repoRoot, "inner/tracked")).toBe("base\n")
  expect(await git(join(f.repoRoot, "inner"), "status", "--porcelain")).toBe("")
})
test("nested failure keeps successful root and identifies partial result", async () => {
  const f = await setup(true)
  await writeFile(join(f.isolationDir, "tracked"), "root\n")
  await writeFile(join(f.isolationDir, "inner/tracked"), "nested\n")
  await commit(join(f.repoRoot, "inner"), "tracked", "conflicting\n")
  const result = await mergeIsolatedChanges(f)
  expect(result.kind).toBe("applied")
  expect(result.changes_applied).toBe(true)
  expect(result.partial).toBe(true)
  expect(result.nested_failed?.[0]?.path).toBe("inner")
  expect(result.nested_failed?.[0]?.error).toContain("patch does not apply")
  expect(await text(f.repoRoot)).toBe("root\n")
  expect(await text(f.repoRoot, "inner/tracked")).toBe("conflicting\n")
})
test("linked parent uses common git directory lock", async () => {
  const f = await setup()
  const linked = join(f.root, "linked")
  await git(f.repoRoot, "worktree", "add", "-b", "linked", linked)
  await commit(f.isolationDir, "new")
  let lockPath = ""
  const result = await mergeIsolatedChanges({ ...f, repoRoot: linked, mode: "branch", lockHook: async (event, path) => {
    if (event === "acquired") { lockPath = path; expect((await stat(path)).isFile()).toBe(true) }
  } })
  expect(result.kind).toBe("branch-merged")
  expect(lockPath).toBe(join(await git(linked, "rev-parse", "--path-format=absolute", "--git-common-dir"), "omo-isolation-merge.lock"))
  expect(await text(linked, "new")).toBe("new\n")
})
test.each(["patch", "branch"] as const)("concurrent %s merges serialize acquire/release without timing assertions", async (mode: "patch" | "branch") => {
  const f = await setup()
  await writeFile(join(f.isolationDir, "one"), "one\n")
  const other = join(f.root, "other")
  await cp(f.repoRoot, other, { recursive: true })
  await writeFile(join(other, "two"), "two\n")
  const entered = Promise.withResolvers<void>()
  const release = Promise.withResolvers<void>()
  const queued = Promise.withResolvers<void>()
  const events: string[] = []
  const first = mergeIsolatedChanges({ ...f, mode, lockHook: async event => {
    events.push(`first:${event}`)
    if (event === "acquired") { entered.resolve(); await release.promise }
  } })
  await entered.promise
  const second = mergeIsolatedChanges({ ...f, mode, id: "second", isolationDir: other, lockHook: event => {
    events.push(`second:${event}`)
    if (event === "waiting") queued.resolve()
  } })
  await queued.promise
  release.resolve()
  const results = await Promise.all([first, second])
  const kind = mode === "patch" ? "applied" : "branch-merged"
  expect(results.map(r => r.kind)).toEqual([kind, kind])
  expect(events).toEqual(["first:waiting", "first:acquired", "second:waiting", "first:released", "second:acquired", "second:released"])
  expect(await text(f.repoRoot, "one")).toBe("one\n")
  expect(await text(f.repoRoot, "two")).toBe("two\n")
}, 15000)
test("dirty baseline filters user WIP out of each child commit", async () => {
  const f = await setup()
  await writeFile(join(f.repoRoot, "tracked"), "user WIP\n")
  await writeFile(join(f.repoRoot, "user-file"), "user untracked\n")
  const baseline = await captureBaseline(f.repoRoot)
  const isolationDir = join(f.root, "dirty-child")
  await cp(f.repoRoot, isolationDir, { recursive: true })
  await git(isolationDir, "add", ".")
  await commit(isolationDir, "first")
  await commit(isolationDir, "second")
  const result = await mergeIsolatedChanges({ ...f, baseline, isolationDir, mode: "branch" })
  expect(result.kind).toBe("branch-merged")
  expect(await git(f.repoRoot, "log", "-2", "--format=%s")).toBe("second\nfirst")
  expect(await git(f.repoRoot, "show", "HEAD:tracked")).toBe("base")
  expect(await git(f.repoRoot, "ls-tree", "--name-only", "HEAD")).not.toContain("user-file")
  expect(await text(f.repoRoot)).toBe("user WIP\n")
  expect(await text(f.repoRoot, "user-file")).toBe("user untracked\n")
})
test("dirty baseline overlapping commit fails with typed commit identity and retained branch", async () => {
  const f = await setup()
  await writeFile(join(f.repoRoot, "tracked"), "user WIP\n")
  const baseline = await captureBaseline(f.repoRoot)
  const isolationDir = join(f.root, "dirty-child")
  await cp(f.repoRoot, isolationDir, { recursive: true })
  await commit(isolationDir, "tracked", "overlapping child\n")
  const sha = await git(isolationDir, "rev-parse", "HEAD")
  let failure: unknown
  try { await commitToBranch(isolationDir, f.repoRoot, f.id, baseline) } catch (error) { failure = error }
  expect(failure).toBeInstanceOf(IsolationCommitReplayError)
  expect((failure as IsolationCommitReplayError).commit).toBe(sha)
  expect(await text(f.repoRoot)).toBe("user WIP\n")
  expect(await git(f.repoRoot, "branch", "--list", "omo/task/test")).toContain("omo/task/test")
})

test("malformed patch reports not-applied without touching parent", async () => {
  const f = await setup()
  const result = await mergeIsolatedChanges({ ...f, delta: { rootPatch: "invalid patch\n", nestedPatches: [] } })
  expect(result.kind).toBe("not-applied")
  expect(result.changes_applied).toBe(false)
  expect(result.conflict).toBeTruthy()
  expect(await git(f.repoRoot, "status", "--porcelain")).toBe("")
})
test("same root and nested delta twice does not create spurious nested failure", async () => {
  const f = await setup(true)
  await writeFile(join(f.isolationDir, "tracked"), "root\n")
  await writeFile(join(f.isolationDir, "inner/tracked"), "nested\n")
  const delta = await captureDeltaPatch(f.isolationDir, f.baseline)
  expect((await mergeIsolatedChanges({ ...f, delta })).kind).toBe("applied")
  const head = await git(join(f.repoRoot, "inner"), "rev-parse", "HEAD")
  const result = await mergeIsolatedChanges({ ...f, delta })
  expect(result.kind).toBe("already-applied")
  expect(result.partial).toBeUndefined()
  expect(await git(join(f.repoRoot, "inner"), "rev-parse", "HEAD")).toBe(head)
})
