// GENERATED by scripts/generate-engine-schema.ts from crates/senpi-desktop-core/schema/engine.schema.json.
// Do not edit by hand; run `bun run --cwd packages/senpi-desktop-protocol generate`.

/** Engine protocol version the host must see in `engine.hello`. */
export const PROTOCOL_VERSION = "1" as const;

/** Engine ABI sentinel the host must see in `engine.hello`. */
export const ENGINE_ABI = "senpi-desktop/1" as const;

/** Every engine JSON-RPC method, by wire name, in schema order. */
export const ENGINE_METHODS = [
	"engine.hello",
	"session.open",
	"session.close",
	"capabilities",
	"displays",
	"windows",
	"capture",
	"click",
	"moveMouse",
	"drag",
	"scroll",
	"typeText",
	"keyChord",
	"raiseWindow",
	"clipboard.read",
	"clipboard.write",
	"ax.snapshot",
	"ax.query",
	"ax.elementAt",
	"ax.focused",
	"ax.node",
	"ax.attributes",
	"ax.children",
	"ax.parent",
	"ax.perform",
	"ax.setValue",
	"ax.focus",
	"ax.click",
	"stopPath.start",
	"stopPath.status",
	"stopPath.heartbeat",
	"stopPath.stop",
	"stopPath.resume",
	"$/cancel",
	"$/test.advanceClock",
] as const;

/** Every server-to-client notification, by wire name. */
export const ENGINE_NOTIFICATIONS = [
	"audit",
	"stopPath.changed",
	"engine.log",
] as const;

/** The frozen desktop error vocabulary mirrored from core `ErrorCode`. */
export const ERROR_CODES = [
	"PermissionDenied",
	"CaptureFailed",
	"InputFailed",
	"BackgroundUnavailable",
	"WindowNotFound",
	"InvalidTarget",
	"InvalidKey",
	"InvalidCoordinateFrame",
	"StaleRef",
	"AxUnsupported",
	"AxFailed",
	"Timeout",
	"Closed",
	"Internal",
	"StopPathUnavailable",
	"Suspended",
	"ScreenLocked",
	"Cancelled",
	"CursorRestoreFailed",
	"FocusRestoreFailed",
	"TransactionFailed",
] as const;

export type EngineMethod = (typeof ENGINE_METHODS)[number];
export type EngineNotification = (typeof ENGINE_NOTIFICATIONS)[number];
export type ErrorCode = (typeof ERROR_CODES)[number];
