/// <reference types="bun-types" />

import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"

describe("LazyCodex label workflow", () => {
  test("#given repository automation #when inspected #then LazyCodex labels are created and applied from PR diffs", async () => {
    // given
    const workflow = await readFile(".github/workflows/lazycodex-label.yml", "utf8")

    // when / then
    expect(workflow).toContain("pull_request_target:")
    expect(workflow).toContain("issues:")
    expect(workflow).toContain('LABEL_NAME: "lazycodex"')
    expect(workflow).toContain('GENERATED_LABEL_NAME: "lazycodex-generated"')
    expect(workflow).toContain("gh label create")
    expect(workflow).toContain('gh pr diff "$PR_NUMBER" --name-only')
    expect(workflow).toContain('gh pr edit "$PR_NUMBER" --add-label "$LABEL_NAME"')
    expect(workflow).toContain('gh pr edit "$PR_NUMBER" --add-label "$GENERATED_LABEL_NAME"')
    expect(workflow).toContain('gh issue edit "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --add-label "$GENERATED_LABEL_NAME"')
    expect(workflow).toContain("This PR was generated by LazyCodex")
    expect(workflow).toContain("packages/omo-codex/*")
    expect(workflow).toContain("packages/shared-skills/*")
    expect(workflow).toContain("packages/ast-grep-mcp/*")
    expect(workflow).toContain("packages/git-bash-mcp/*")
    expect(workflow).toContain("packages/lsp-tools-mcp/*")
    expect(workflow).not.toContain("actions/checkout")
  })

  test("#given issue templates #when inspected #then LazyCodex reports can select the lazycodex label", async () => {
    // given
    const template = await readFile(".github/ISSUE_TEMPLATE/lazycodex_bug_report.yml", "utf8")

    // when / then
    expect(template).toContain("name: LazyCodex Bug Report")
    expect(template).toContain('labels: ["bug", "needs-triage", "lazycodex"]')
    expect(template).toContain("LazyCodex version")
    expect(template).toContain("Codex version")
  })
})
