// Regenerates src/engine-schema.generated.ts from the committed engine schema.
// Run: bun run --cwd packages/senpi-desktop-protocol generate
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = join(packageDir, "../../crates/senpi-desktop-core/schema/engine.schema.json");
const outputPath = join(packageDir, "src/engine-schema.generated.ts");

function recordOf(value: unknown, label: string): Record<string, unknown> {
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		throw new Error(`${label} is not an object`);
	}
	return Object.fromEntries(Object.entries(value));
}

function literal(value: unknown, label: string): string | number {
	if (typeof value !== "string" && typeof value !== "number") {
		throw new Error(`${label} is not a string or number literal`);
	}
	return value;
}

const schema = recordOf(JSON.parse(readFileSync(schemaPath, "utf8")), "engine.schema.json");
const protocolVersion = literal(schema.protocolVersion, "protocolVersion");
const abi = literal(schema.abi, "abi");
const methods = Object.keys(recordOf(schema.methods, "methods"));
const notifications = Object.keys(recordOf(schema.notifications, "notifications"));
const errorCodes = Object.keys(recordOf(schema.errors, "errors"));

const list = (items: readonly string[]): string =>
	`[\n${items.map((item) => `\t${JSON.stringify(item)},`).join("\n")}\n]`;

const source = `// GENERATED by scripts/generate-engine-schema.ts from crates/senpi-desktop-core/schema/engine.schema.json.
// Do not edit by hand; run \`bun run --cwd packages/senpi-desktop-protocol generate\`.

/** Engine protocol version the host must see in \`engine.hello\`. */
export const PROTOCOL_VERSION = ${JSON.stringify(protocolVersion)} as const;

/** Engine ABI sentinel the host must see in \`engine.hello\`. */
export const ENGINE_ABI = ${JSON.stringify(abi)} as const;

/** Every engine JSON-RPC method, by wire name, in schema order. */
export const ENGINE_METHODS = ${list(methods)} as const;

/** Every server-to-client notification, by wire name. */
export const ENGINE_NOTIFICATIONS = ${list(notifications)} as const;

/** The frozen desktop error vocabulary mirrored from core \`ErrorCode\`. */
export const ERROR_CODES = ${list(errorCodes)} as const;

export type EngineMethod = (typeof ENGINE_METHODS)[number];
export type EngineNotification = (typeof ENGINE_NOTIFICATIONS)[number];
export type ErrorCode = (typeof ERROR_CODES)[number];
`;

writeFileSync(outputPath, source);
